name: CI

on: [push, pull_request]

jobs:
  build_ps3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build Files
        run: scripts/windows/build_ps3.bat
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GH3DX-PS3
          path: out/ps3

  build_xbox:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build Files
        run: scripts/windows/build_xbox.bat
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: GH3DX-Xbox
          path: out/xbox
